baseurl = "http://example.com"
disablePathToLower = false
languageCode = "es-PE"
theme = "hugo-webmag"
title = "Hugo Roca | Proyectos - Web"
contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"
# Disqus
disqusShortname = "hugorocaproyectos"
# Tamaño de paginación
paginate = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

[params]
  # Disabled/Enabled buscador
  search = false
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 4

  # sidebar links
  github = "https://github.com/parsiya/"
  bitbucket = "https://bitbucket.org/parsiya/"
  twitter = "https://twitter.com/cryptogangsta/"
  keybase = "https://keybase.io/parsiya/"
  stackoverflow = ""
  linkedin = ""
  googleplus = ""
  youtube = ""
  facebook = ""
  instagram = ""

  # --- End sidebar options ---

  # Author's name (appears in meta tags and under posts)
  author = "Hugo Roca"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  # googleAnalytics = "UA-XXXXX-X"

  # Website's default description
  defaultDescription = ""
  
  # Remove or set to false to use FontAwesome CDN, otherwise the theme uses ForkAwesome local fonts.
  # fontAwesome = false

  # Generate taxonomy pages
  generateTaxonomyList = true

  # This is not needed unless alphabetical sort is needed
  # sortTaxonomyAlphabetical = true

  # Twitter card config
  # Enable with this.
  # twitterCardEnabled = true
  # Don't include the @.
  # twitterCardSite = 
  # twitterCardDomain = "parsiya.net"
  # Don't include the @.
  # twitterCardAuthor = "CryptoGangsta"

  # Set to true to enable compact index. Set to false or remove to go back to classic view.
  # compactIndex = true

# Menu ----------------------------------------------------------------------
[[menu.main]]
  Name = "Inicio"
  URL = "/"
  weight = 1

[[menu.main]]
  Name = "JavaScript"
  URL = "/categories/javascript/"
  weight = 2

[[menu.main]]
  Name = "C Sharp"
  URL = "/categories/c-sharp/"
  weight = 3

[[menu.main]]
  Name = "PHP"
  URL = "/categories/php"
  weight = 4

[[menu.main]]
  Name = "Base de datos"
  URL = "/categories/base-de-datos"
  weight = 5

[[menu.main]]
  Name = "Sistemas"
  URL = "/categories/sistemas/"
  weight = 6
# Sidebar menus ---------------------------------------------------------------

[[menu.sidebar]]
  Name = "Inicio"
  URL = "/"

[[menu.sidebar]]
  Name = "Acerca de mí"
  URL = "https://hugoroca.github.io"
  weight = 0